-- schema_v70_risk_library_seed.sql
-- Populates risk_library with sector-specific risks across all pillars.
-- Clears and re-seeds the table so this migration is idempotent.

TRUNCATE TABLE risk_library RESTART IDENTITY;

INSERT INTO risk_library (pillar, sector, risk_detail, typical_cause, typical_impact, treatment_strategy) VALUES

-- ══════════════════════════════════════════════════════════════
-- ALL SECTORS (generic risks applicable to any organisation)
-- ══════════════════════════════════════════════════════════════
('Strategic',  'All Sectors', 'Failure to achieve strategic objectives due to inadequate planning or execution', 'Poorly defined strategy; lack of leadership alignment; resource constraints', 'Missed growth targets; reputational damage; loss of competitive position', 'Robust strategic planning cycle; KPI tracking; Board-level oversight'),
('Finance',    'All Sectors', 'Revenue concentration on single product, client, or market segment', 'Organic growth without diversification; market conditions', 'Vulnerability to sector downturn; existential risk from loss of key client', 'Revenue diversification strategy; pipeline monitoring; new service development'),
('Finance',    'All Sectors', 'Inadequate liquidity to meet short-term obligations', 'Poor cash flow forecasting; rapid growth consuming working capital', 'Inability to pay suppliers or staff; credit rating downgrade; insolvency', 'Rolling 13-week cash flow forecast; committed credit facilities; liquidity buffer'),
('HR',         'All Sectors', 'Loss of key personnel or critical skills', 'Competitive labour market; inadequate retention programmes', 'Operational disruption; loss of institutional knowledge; recruitment costs', 'Succession planning; retention incentives; knowledge management programme'),
('HR',         'All Sectors', 'Workplace safety incident resulting in injury or fatality', 'Inadequate safety training; non-compliance with HSE procedures', 'Employee harm; regulatory penalties; reputational damage; litigation', 'HSE management system; mandatory safety training; incident reporting culture'),
('IT',         'All Sectors', 'Cyber attack resulting in data breach or system compromise', 'Phishing; unpatched vulnerabilities; insider threat; weak access controls', 'Data loss; regulatory fines; reputational damage; operational disruption', 'Multi-layer cybersecurity controls; SOC monitoring; incident response plan'),
('IT',         'All Sectors', 'Unplanned IT system downtime affecting business operations', 'Hardware failure; software bugs; inadequate redundancy', 'Revenue loss; customer dissatisfaction; SLA breach', 'High-availability architecture; DR plan; RTO/RPO targets; tested failover'),
('Compliance', 'All Sectors', 'Non-compliance with applicable laws or regulations', 'Inadequate compliance monitoring; regulatory change not tracked', 'Fines; licence suspension; reputational damage; litigation', 'Compliance obligations register; regular horizon scanning; staff training'),
('Governance', 'All Sectors', 'Fraud or financial misappropriation by employees or third parties', 'Weak internal controls; inadequate segregation of duties; poor culture', 'Financial loss; reputational damage; regulatory action', 'Segregation of duties; internal audit; whistleblower hotline; background checks'),
('Security',   'All Sectors', 'Physical security breach at facilities', 'Inadequate access controls; tailgating; inadequate CCTV coverage', 'Theft; data breach; harm to employees', 'Access control systems; CCTV; security personnel; visitor management'),
('Operations', 'All Sectors', 'Third-party / supplier failure disrupting operations', 'Over-reliance on single supplier; inadequate vendor due diligence', 'Supply chain disruption; service degradation; reputational damage', 'Supplier diversification; contractual SLAs; vendor risk assessments; BCPs'),
('BCM',        'All Sectors', 'Business continuity failure following a major disruption event', 'Inadequate BCP; untested recovery plans; single points of failure', 'Extended downtime; financial loss; regulatory breach; reputational damage', 'Tested BCP/DRP; alternate site arrangements; crisis management team'),

-- ══════════════════════════════════════════════════════════════
-- GOVERNMENT
-- ══════════════════════════════════════════════════════════════
('Strategic',  'Government', 'Failure to deliver national or ministerial mandate on time', 'Unclear objectives; funding delays; inter-agency coordination gaps', 'Public dissatisfaction; political consequences; audit findings', 'Clear mandate definition; programme governance; ministerial reporting'),
('Strategic',  'Government', 'Policy decision leads to unintended socioeconomic consequences', 'Inadequate impact assessment; insufficient stakeholder consultation', 'Public backlash; reversal costs; loss of public trust', 'Rigorous policy impact assessment; pilot programmes; stakeholder engagement'),
('Governance', 'Government', 'Corruption or abuse of public office', 'Weak internal controls; inadequate oversight; culture of impunity', 'Criminal liability; reputational damage; loss of public trust', 'Anti-corruption framework; asset declarations; internal audit; whistleblower channels'),
('Compliance', 'Government', 'Non-compliance with public procurement regulations', 'Lack of awareness; pressure to expedite; inadequate controls', 'Contract voidance; audit findings; reputational damage; criminal liability', 'Procurement policy; mandatory approvals; regular training; audit reviews'),
('Finance',    'Government', 'Budget overrun on government programmes or infrastructure projects', 'Poor cost estimation; scope creep; inflation; contractor delays', 'Reduced funds for other services; audit findings; political consequences', 'Robust project governance; contingency budgets; PMO oversight'),
('Operations', 'Government', 'Failure of critical public service delivery (e.g. utilities, health, postal)', 'Ageing infrastructure; workforce gaps; system failures', 'Public harm; political pressure; reputational damage', 'Service continuity planning; infrastructure investment; SLA monitoring'),
('IT',         'Government', 'Cyber attack on critical national infrastructure or government systems', 'Nation-state actors; unpatched legacy systems; insider threats', 'Disruption of public services; national security risk; data breach', 'NCSC-aligned cybersecurity framework; air-gapped critical systems; incident response'),
('HR',         'Government', 'Nationalisation / workforce localisation targets not met', 'Insufficient qualified nationals; inadequate training pipelines', 'Regulatory penalties; licence risk; reputational damage', 'Localisation strategy; training academies; succession planning for national talent'),
('Security',   'Government', 'Espionage or intelligence compromise of sensitive government information', 'Insider threat; foreign intelligence operations; poor information classification', 'National security breach; diplomatic consequences; loss of sensitive data', 'Information classification policy; personnel security vetting; SCIF environments'),
('BCM',        'Government', 'Disruption of essential government services during a national emergency', 'Natural disaster; pandemic; cyber attack; political instability', 'Breakdown in public order; failure of critical services; loss of life', 'National emergency response plan; crisis management centre; inter-agency protocols'),

-- ══════════════════════════════════════════════════════════════
-- LOGISTICS & TRANSPORTATION
-- ══════════════════════════════════════════════════════════════
('Operations', 'Logistics & Transportation', 'Delay or loss of shipments causing customer SLA breaches', 'Route disruptions; customs delays; capacity constraints; vehicle breakdowns', 'Customer churn; penalty clauses; reputational damage', 'Real-time tracking; buffer inventory; alternate routing plans; SLA monitoring'),
('Operations', 'Logistics & Transportation', 'Fleet accident or incident resulting in injury or cargo loss', 'Driver fatigue; inadequate vehicle maintenance; poor weather conditions', 'Human harm; cargo loss; insurance claims; reputational damage; regulatory action', 'Driver health checks; fleet telematics; preventative maintenance programme; HSE training'),
('Operations', 'Logistics & Transportation', 'Customs or border compliance failure causing shipment hold', 'Incorrect documentation; regulatory change; restricted goods oversight failure', 'Shipment delays; fines; customer penalties; licence risk', 'Customs compliance team; automated documentation checks; regulatory monitoring'),
('Strategic',  'Logistics & Transportation', 'Disruption from geopolitical events affecting trade routes', 'Regional conflict; trade sanctions; port closures; piracy', 'Route unavailability; cost increases; delivery failures', 'Route diversification; geopolitical risk monitoring; contractual force majeure provisions'),
('Finance',    'Logistics & Transportation', 'Fuel price volatility eroding margin', 'Global oil price fluctuations; hedging strategy failure', 'Margin compression; uncompetitive pricing; contract losses', 'Fuel hedging; fuel surcharge clauses in contracts; fleet efficiency programme'),
('IT',         'Logistics & Transportation', 'Failure of logistics management system causing operational blind spots', 'System outage; data integration failure; software bugs', 'Inability to track shipments; customer dissatisfaction; operational chaos', 'System redundancy; manual fallback procedures; DR plan; vendor SLAs'),
('Compliance', 'Logistics & Transportation', 'Dangerous goods mishandling or mislabelling incident', 'Inadequate staff training; documentation errors; supplier non-compliance', 'Injury; regulatory sanctions; reputational damage; licence suspension', 'Dangerous goods training; documentation controls; supplier audits'),
('HR',         'Logistics & Transportation', 'Driver shortage impacting service capacity', 'Ageing workforce; high turnover; licensing requirements', 'Reduced capacity; SLA breaches; revenue loss', 'Driver recruitment pipeline; retention incentives; third-party fleet partnerships'),
('Security',   'Logistics & Transportation', 'Cargo theft or tampering during transit', 'Inadequate security controls; insider collusion; high-value cargo targeting', 'Financial loss; customer trust damage; insurance premium increase', 'GPS tracking; tamper-evident seals; secure parking; background checks for drivers'),
('BCM',        'Logistics & Transportation', 'Natural disaster or extreme weather disrupting distribution network', 'Flooding; storms; earthquakes affecting routes or warehouses', 'Network shutdown; stock losses; customer SLA breach', 'Weather monitoring; alternate routing; warehouse diversification; BCP testing'),

-- ══════════════════════════════════════════════════════════════
-- FINANCIAL SERVICES
-- ══════════════════════════════════════════════════════════════
('Finance',    'Financial Services', 'Credit risk — borrower default causing loan loss', 'Economic downturn; borrower financial deterioration; inadequate underwriting', 'Loan impairments; reduced profitability; capital adequacy breach', 'Robust credit underwriting; portfolio diversification; credit risk monitoring; IFRS 9 provisioning'),
('Finance',    'Financial Services', 'Market risk — adverse movement in interest rates, FX, or equity prices', 'Rate changes; currency movements; portfolio concentration', 'Mark-to-market losses; NIM compression; hedging costs', 'VaR limits; hedging strategy; ALM committee oversight; stress testing'),
('Finance',    'Financial Services', 'Liquidity risk — inability to meet funding obligations', 'Deposit outflows; wholesale funding market closure; asset-liability mismatch', 'Liquidity crisis; reputational damage; regulatory intervention', 'LCR/NSFR compliance; diversified funding base; liquidity contingency plan'),
('Compliance', 'Financial Services', 'AML/CFT compliance failure resulting in regulatory sanction', 'Inadequate KYC/CDD; transaction monitoring gaps; sanctions screening failure', 'Regulatory fines; licence revocation; reputational damage', 'Robust AML programme; automated transaction monitoring; sanctions screening; staff training'),
('Compliance', 'Financial Services', 'Regulatory capital breach (Basel III/IV requirements)', 'Unexpected losses; rapid asset growth; model error', 'Regulatory intervention; dividend restriction; reputational damage', 'Capital adequacy monitoring; ICAAP; stress testing; capital buffer management'),
('IT',         'Financial Services', 'Core banking system outage disrupting customer transactions', 'Software failure; cyber attack; infrastructure collapse', 'Customer dissatisfaction; reputational damage; regulatory scrutiny; revenue loss', 'Active-active architecture; DR testing; vendor SLAs; operational resilience programme'),
('Governance', 'Financial Services', 'Mis-selling of financial products to retail customers', 'Incentive structures; inadequate suitability assessments; poor training', 'Regulatory fines; compensation costs; reputational damage; licence risk', 'Suitability framework; conduct risk monitoring; product governance; staff training'),
('Security',   'Financial Services', 'Payment fraud resulting in customer financial loss', 'Account takeover; card skimming; social engineering; insider fraud', 'Financial losses; customer compensation; reputational damage', 'Multi-factor authentication; fraud detection systems; customer education; rapid response'),

-- ══════════════════════════════════════════════════════════════
-- ISLAMIC FINANCE
-- ══════════════════════════════════════════════════════════════
('Compliance', 'Islamic Finance', 'Sharia non-compliance in product structuring or operations', 'Inadequate Sharia review; evolving scholarly opinions; documentation errors', 'Product invalidation; reputational damage; customer trust loss; regulatory sanction', 'Robust Sharia governance; SSB oversight; fatwa documentation; internal Sharia audit'),
('Compliance', 'Islamic Finance', 'AAOIFI / IFSB regulatory compliance failure', 'Lack of awareness; capacity gaps; interpretation differences', 'Regulatory sanction; reputational damage; competitive disadvantage', 'Compliance monitoring; regulatory horizon scanning; staff training; external audit'),
('Finance',    'Islamic Finance', 'Profit rate risk on Murabaha or Ijarah contracts in rising rate environment', 'Fixed profit rate contracts vs. rising benchmark rates', 'NIM compression; competitive disadvantage; repricing mismatch', 'Variable rate clauses; portfolio repricing strategy; hedging using Sharia-compliant instruments'),
('Governance', 'Islamic Finance', 'Conflict of interest or independence compromise of Sharia Supervisory Board', 'Board members serving multiple institutions; commercial pressure', 'Sharia opinions influenced by commercial interests; credibility loss', 'SSB independence policy; disclosure requirements; rotation policy; SSB charter'),
('Operations', 'Islamic Finance', 'Mudarabah or Musharakah investment loss due to partner mismanagement', 'Inadequate partner due diligence; misaligned incentives; economic downturn', 'Financial loss; reputational damage; investor trust erosion', 'Robust partner due diligence; governance covenants; monitoring reporting; exit provisions'),

-- ══════════════════════════════════════════════════════════════
-- HEALTHCARE
-- ══════════════════════════════════════════════════════════════
('Operations', 'Healthcare', 'Patient safety incident resulting in harm or death', 'Clinical error; medication mistake; equipment failure; staff fatigue', 'Patient harm; litigation; regulatory sanction; licence risk', 'Clinical governance; mandatory incident reporting; root cause analysis; staff training'),
('Compliance', 'Healthcare', 'Data breach exposing patient health information', 'Cyber attack; inadequate access controls; staff error', 'Regulatory fines (HIPAA/GDPR); reputational damage; patient trust loss', 'Data encryption; access controls; staff training; DPA compliance programme'),
('HR',         'Healthcare', 'Clinical staff shortage affecting care quality and capacity', 'Global healthcare workforce deficit; burnout; licensing bottlenecks', 'Reduced care capacity; quality compromise; staff stress cascade', 'Workforce planning; staff retention programmes; locum/agency partnerships'),
('Finance',    'Healthcare', 'Medical malpractice claims exceeding insurance coverage', 'Clinical errors; patient expectations; litigation culture', 'Financial liability; reputational damage; insurance premium increases', 'Robust clinical governance; adequate malpractice coverage; claims management'),
('IT',         'Healthcare', 'Ransomware attack on clinical systems disrupting patient care', 'Unpatched systems; phishing; legacy infrastructure', 'Clinical delays; patient harm risk; ransom payment; regulatory scrutiny', 'Cyber resilience programme; offline backups; incident response; staff phishing training'),
('Compliance', 'Healthcare', 'Non-compliance with healthcare facility accreditation standards', 'Inadequate quality management; resource constraints; documentation gaps', 'Accreditation loss; reputational damage; contract termination by insurers', 'Accreditation readiness programme; internal audit; continuous quality improvement'),

-- ══════════════════════════════════════════════════════════════
-- TECHNOLOGY
-- ══════════════════════════════════════════════════════════════
('IT',         'Technology', 'Critical software vulnerability exploited by threat actors', 'Zero-day vulnerabilities; delayed patching; third-party dependencies', 'Data breach; service disruption; financial and reputational damage', 'Vulnerability management programme; responsible disclosure process; bug bounty; SDLC security'),
('Strategic',  'Technology', 'Technology product becomes obsolete due to market disruption', 'Disruptive entrants; emerging technologies; failure to innovate', 'Revenue decline; market share loss; talent drain', 'R&D investment; technology horizon scanning; agile product development; M&A strategy'),
('Compliance', 'Technology', 'Data privacy violation under GDPR, PDPL, or local data protection law', 'Inadequate data governance; third-party sharing without consent; breach', 'Regulatory fines; reputational damage; litigation; customer churn', 'Privacy by design; data governance programme; DPO appointment; consent management'),
('HR',         'Technology', 'Loss of key technical talent to competitors', 'Competitive compensation; limited career progression; remote work flexibility gaps', 'Critical project delays; knowledge loss; recruitment costs', 'Competitive compensation; equity/LTIP; career development; retention bonuses'),
('Finance',    'Technology', 'Failure to achieve projected revenue from new product launch', 'Overestimated demand; delayed go-to-market; competitive response', 'Revenue shortfall; investor disappointment; cost overrun', 'Market validation before launch; agile MVPs; go-to-market governance'),
('Security',   'Technology', 'Insider threat — malicious exfiltration of source code or customer data', 'Disgruntled employee; inadequate access controls; poor offboarding', 'IP theft; competitive harm; regulatory consequences; customer breach', 'Zero-trust architecture; DLP tools; privileged access management; offboarding checklist'),

-- ══════════════════════════════════════════════════════════════
-- PROFESSIONAL SERVICES
-- ══════════════════════════════════════════════════════════════
('Governance', 'Professional Services', 'Professional liability claim arising from negligent advice', 'Advice error; scope misunderstanding; inadequate quality control', 'Legal liability; reputational damage; insurance premium increase', 'Quality review processes; engagement scoping; PI insurance; client communication protocols'),
('Compliance', 'Professional Services', 'Independence or conflict of interest violation', 'Undisclosed relationships; cross-service conflicts; partner relationships', 'Licence sanction; engagement invalidation; reputational damage', 'Conflict check system; independence policies; mandatory disclosure; annual confirmations'),
('HR',         'Professional Services', 'Key partner or senior expert departure taking client relationships', 'Inadequate retention; competing offers; retirement', 'Client loss; revenue decline; team morale impact', 'Succession planning; client relationship diversification; non-compete agreements; retention'),
('Finance',    'Professional Services', 'Project cost overrun due to scope creep or under-estimation', 'Poor scoping; client-driven changes; underestimated complexity', 'Margin erosion; write-offs; client disputes', 'Robust scoping and change control; project governance; regular billing reviews'),
('Strategic',  'Professional Services', 'Failure to win sufficient new mandates to sustain growth', 'Competitive market; inadequate business development; weak differentiation', 'Revenue stagnation; talent retention risk; margin pressure', 'BD strategy; thought leadership; strategic account management; pipeline governance'),

-- ══════════════════════════════════════════════════════════════
-- OIL & GAS (UPSTREAM)
-- ══════════════════════════════════════════════════════════════
('Operations', 'Oil & Gas (Upstream)', 'Well blowout or uncontrolled release causing injury, death, or environmental damage', 'Equipment failure; pressure miscalculation; inadequate well control procedures', 'Fatalities; environmental catastrophe; licence suspension; litigation', 'Well control programme; blowout preventer testing; NORM management; emergency response'),
('Strategic',  'Oil & Gas (Upstream)', 'Sustained low oil price rendering projects economically unviable', 'Global supply-demand imbalance; OPEC decisions; energy transition', 'Project write-downs; capital programme cuts; workforce reductions', 'Breakeven price management; portfolio diversification; cost reduction programmes'),
('Compliance', 'Oil & Gas (Upstream)', 'Environmental regulatory violation causing pollution', 'Spill; flaring non-compliance; inadequate waste management', 'Regulatory fines; licence suspension; reputational damage; remediation costs', 'Environmental management system; real-time monitoring; incident response; ISO 14001'),
('HR',         'Oil & Gas (Upstream)', 'Skilled workforce shortage in specialist technical roles', 'Ageing workforce; competition for talent; remote location deterrence', 'Project delays; safety risks from inexperience; cost increases', 'Graduate programmes; technical training; competitive packages; succession planning'),
('Finance',    'Oil & Gas (Upstream)', 'Capital project cost overrun on major upstream development', 'Scope changes; equipment supply delays; contractor performance; FX', 'Profitability impact; investor disappointment; balance sheet pressure', 'Project governance; contingency budgets; EPC contract structures; PMO oversight'),
('Security',   'Oil & Gas (Upstream)', 'Sabotage or terrorist attack on upstream facilities', 'Geopolitical instability; activist targeting; organised crime', 'Production loss; employee harm; asset damage; environmental damage', 'Security risk assessment; physical protection measures; community engagement; crisis management'),

-- ══════════════════════════════════════════════════════════════
-- OIL & GAS (DOWNSTREAM)
-- ══════════════════════════════════════════════════════════════
('Operations', 'Oil & Gas (Downstream)', 'Refinery fire, explosion, or toxic release causing casualties and shutdown', 'Process safety failure; equipment degradation; human error', 'Fatalities; production loss; regulatory action; reputational damage', 'Process safety management; HAZOP studies; preventative maintenance; emergency response'),
('Finance',    'Oil & Gas (Downstream)', 'Refinery margin compression due to crude-product spread narrowing', 'Global product oversupply; feedstock cost increase; competitive dynamics', 'Reduced EBITDA; asset impairment risk; dividend pressure', 'Feedstock diversification; upgrading investments; margin hedging; operational efficiency'),
('Compliance', 'Oil & Gas (Downstream)', 'Product quality failure resulting in off-spec fuel supplied to market', 'Blending error; laboratory error; contamination', 'Liability claims; regulatory sanction; reputational damage; product recall', 'Quality management system; lab controls; independent testing; product liability insurance'),

-- ══════════════════════════════════════════════════════════════
-- MANUFACTURING
-- ══════════════════════════════════════════════════════════════
('Operations', 'Manufacturing', 'Production line shutdown due to equipment failure or unplanned maintenance', 'Ageing equipment; inadequate preventive maintenance; spare parts unavailability', 'Lost production; customer delivery failure; overtime cost', 'Predictive maintenance programme; critical spare parts inventory; equipment lifecycle management'),
('Operations', 'Manufacturing', 'Product recall due to quality defect or safety issue', 'Manufacturing defect; component failure; process deviation', 'Recall costs; liability; reputational damage; customer loss', 'Quality management system (ISO 9001); statistical process control; testing protocols'),
('Finance',    'Manufacturing', 'Raw material cost increase eroding product margins', 'Commodity price volatility; supply chain disruption; FX movements', 'Margin compression; uncompetitive pricing; customer loss', 'Commodity hedging; supply diversification; contract pricing mechanisms; cost pass-through'),
('Strategic',  'Manufacturing', 'Loss of major customer contract representing significant revenue share', 'Competitor offering; pricing pressure; relationship failure; product quality', 'Revenue decline; under-utilised capacity; workforce impact', 'Customer diversification; key account management; long-term supply agreements'),
('Compliance', 'Manufacturing', 'Workplace safety non-compliance resulting in injury or regulatory action', 'Inadequate HSE controls; training gaps; safety culture weakness', 'Injury/fatality; regulatory fines; production shutdown; reputational damage', 'HSE management system; regular audits; safety training; incident reporting culture'),

-- ══════════════════════════════════════════════════════════════
-- RETAIL
-- ══════════════════════════════════════════════════════════════
('Strategic',  'Retail', 'Loss of market share to online competitors or changing consumer preferences', 'E-commerce growth; consumer shift; failure to innovate', 'Revenue decline; store closures; margin pressure', 'Omnichannel strategy; digital investment; loyalty programmes; customer analytics'),
('Operations', 'Retail', 'Supply chain disruption resulting in out-of-stock situations', 'Supplier failure; port congestion; demand forecasting error', 'Lost sales; customer dissatisfaction; markdown costs', 'Supplier diversification; safety stock; demand forecasting tools; supply chain visibility'),
('IT',         'Retail', 'E-commerce platform outage during peak trading period', 'Traffic surge; software failure; DDoS attack', 'Revenue loss; customer dissatisfaction; reputational damage', 'Cloud scalability; load testing; DDoS protection; DR plan; on-call support'),
('Finance',    'Retail', 'Inventory shrinkage due to theft or administrative error', 'Shoplifting; employee theft; poor stock management', 'Direct financial loss; margin erosion; operational disruption', 'Loss prevention programme; CCTV; stock reconciliation; audit controls'),
('Compliance', 'Retail', 'Consumer protection or product safety regulatory breach', 'Unsafe products; misleading marketing; pricing errors', 'Regulatory fines; product withdrawal; reputational damage; litigation', 'Product safety testing; legal review of marketing; compliance monitoring'),

-- ══════════════════════════════════════════════════════════════
-- TELECOMMUNICATIONS
-- ══════════════════════════════════════════════════════════════
('Operations', 'Telecommunications', 'Network outage causing widespread service disruption', 'Hardware failure; software bug; natural disaster; capacity overload', 'Revenue loss; regulatory fine; customer churn; reputational damage', 'Network redundancy; real-time monitoring; DR plan; SLA management'),
('Strategic',  'Telecommunications', 'Loss of market share due to disruptive new entrant or technology', 'OTT services; price competition; 5G disruption by new licensees', 'Revenue decline; ARPU erosion; customer churn', '5G investment; service innovation; bundling strategy; customer retention'),
('Compliance', 'Telecommunications', 'Regulatory licence condition breach or spectrum violation', 'Technical non-compliance; inadequate monitoring; regulatory change', 'Licence suspension; fines; reputational damage', 'Regulatory compliance programme; spectrum monitoring; proactive regulator engagement'),
('Security',   'Telecommunications', 'SIM swap fraud or signalling attack (SS7/Diameter) enabling account takeover', 'Inadequate SIM swap controls; SS7 network vulnerabilities', 'Customer financial loss; reputational damage; regulatory scrutiny', 'SIM swap authentication controls; SS7 monitoring; fraud detection; customer alerts'),
('IT',         'Telecommunications', 'Data centre failure impacting core network and customer services', 'Power failure; cooling failure; fire; hardware failure', 'Network disruption; data loss; revenue impact; SLA breach', 'Tier III/IV data centres; UPS and generator backup; active-active configuration; DR'),

-- ══════════════════════════════════════════════════════════════
-- AVIATION
-- ══════════════════════════════════════════════════════════════
('Operations', 'Aviation', 'Aircraft accident or serious incident causing fatalities', 'Mechanical failure; human error; ATC failure; adverse weather', 'Loss of life; fleet grounding; reputational damage; criminal liability', 'Safety management system (SMS); IOSA certification; crew training; maintenance programme'),
('Compliance', 'Aviation', 'Regulatory non-compliance with ICAO/GCAA/EASA airworthiness standards', 'Maintenance lapses; documentation errors; inadequate oversight', 'Aircraft grounding; operating certificate suspension; reputational damage', 'Airworthiness compliance programme; regular authority audits; maintenance documentation'),
('Finance',    'Aviation', 'Jet fuel cost spike significantly increasing operating costs', 'Oil price volatility; refinery disruption; geopolitical events', 'Margin compression; route unprofitability; cash pressure', 'Fuel hedging; fuel efficiency programmes; surcharge mechanisms'),
('Strategic',  'Aviation', 'Demand collapse due to pandemic, geopolitical event, or economic recession', 'External macroeconomic shocks beyond airline control', 'Revenue collapse; fleet overcapacity; workforce reduction', 'Fleet flexibility; route diversification; government support mechanisms; liquidity reserves'),
('HR',         'Aviation', 'Shortage of qualified pilots or engineers', 'Global aviation growth outpacing training pipeline; ageing workforce', 'Route cancellations; capacity constraints; safety risk from inexperienced staff', 'Cadet programme; competitive packages; type rating investment; retention bonuses'),

-- ══════════════════════════════════════════════════════════════
-- CONSTRUCTION & REAL ESTATE
-- ══════════════════════════════════════════════════════════════
('Operations', 'Construction & Real Estate', 'Construction worker fatality or serious injury on site', 'Falls from height; plant collision; excavation collapse; inadequate PPE', 'Criminal liability; project shutdown; reputational damage; civil claims', 'Site safety management; permit-to-work; toolbox talks; regular HSE audits'),
('Finance',    'Construction & Real Estate', 'Project cost overrun due to design changes, material inflation, or delays', 'Scope changes; commodity inflation; contractor underperformance; weather', 'Reduced return on investment; cash flow strain; funder default', 'Fixed-price contracts where possible; contingency; change control governance; EVM'),
('Strategic',  'Construction & Real Estate', 'Property market downturn reducing asset values and sales velocity', 'Interest rate rises; oversupply; economic slowdown; regulatory changes', 'Asset impairment; reduced revenue; covenant breach; project viability risk', 'Portfolio diversification; pre-sales strategy; LTV management; flexible phasing'),
('Compliance', 'Construction & Real Estate', 'Building code or planning permission non-compliance', 'Design errors; contractor shortcuts; regulation change post-approval', 'Stop-work order; demolition order; fines; reputational damage', 'Compliance checks at design stage; inspections at key milestones; regulatory monitoring'),

-- ══════════════════════════════════════════════════════════════
-- UTILITIES
-- ══════════════════════════════════════════════════════════════
('Operations', 'Utilities', 'Grid failure or extended power outage affecting large populations', 'Equipment failure; extreme weather; cyber attack; demand spike', 'Public disruption; economic damage; regulatory scrutiny; reputational damage', 'Grid redundancy; demand response; emergency response plan; regulatory reporting'),
('Compliance', 'Utilities', 'Environmental permit breach from water or air pollution incident', 'Infrastructure failure; capacity overload; inadequate monitoring', 'Regulatory fines; remediation costs; licence conditions; reputational damage', 'Environmental management system; real-time monitoring; emergency response; ISO 14001'),
('Strategic',  'Utilities', 'Stranded asset risk from energy transition (fossil fuel infrastructure)', 'Accelerating renewable energy adoption; regulatory decarbonisation targets', 'Asset impairment; capital write-down; stranded investment', 'Energy transition strategy; renewable investment; asset life management; stakeholder engagement'),
('Finance',    'Utilities', 'Regulatory price control reducing permissible revenues', 'Government or regulator imposing lower allowed returns or tariffs', 'Revenue reduction; capital programme deferral; profitability pressure', 'Constructive regulatory engagement; efficiency programmes; cost reduction'),

-- ══════════════════════════════════════════════════════════════
-- HOSPITALITY & TOURISM
-- ══════════════════════════════════════════════════════════════
('Strategic',  'Hospitality & Tourism', 'Demand collapse due to geopolitical event, pandemic, or economic downturn', 'Travel restrictions; safety concerns; economic recession; political instability', 'Revenue collapse; high fixed cost exposure; workforce impact', 'Revenue diversification; flexible cost base; domestic market strategy; cash reserves'),
('Operations', 'Hospitality & Tourism', 'Food safety incident causing guest illness or fatality', 'Inadequate food hygiene; supplier contamination; staff training gaps', 'Guest harm; reputational damage; regulatory action; litigation', 'HACCP programme; supplier audits; food safety training; incident response'),
('HR',         'Hospitality & Tourism', 'High staff turnover in guest-facing roles affecting service quality', 'Seasonal demand; low wages; physically demanding work; limited career paths', 'Service quality decline; training costs; customer satisfaction impact', 'Competitive compensation; employee engagement; career development; employer branding'),
('Security',   'Hospitality & Tourism', 'Security incident at hotel or tourist attraction causing harm to guests', 'Terrorism; criminal activity; inadequate security controls', 'Guest harm; reputational damage; liability; destination image damage', 'Security risk assessment; trained security personnel; emergency response; CCTV'),

-- ══════════════════════════════════════════════════════════════
-- TRADING
-- ══════════════════════════════════════════════════════════════
('Finance',    'Trading', 'Commodity price movement causing inventory valuation loss', 'Market volatility; geopolitical events; supply-demand shifts', 'Inventory write-down; margin erosion; cash flow pressure', 'Hedging strategy; inventory turnover targets; price risk limits; mark-to-market monitoring'),
('Operations', 'Trading', 'Counterparty default on trade settlement', 'Counterparty insolvency; dispute; FX movement; payment system failure', 'Financial loss; liquidity pressure; relationship damage', 'Counterparty credit assessment; trade credit insurance; collateral requirements; netting agreements'),
('Compliance', 'Trading', 'Import/export sanctions violation', 'Inadequate sanctions screening; third-party non-compliance; rapid regulatory change', 'Criminal liability; licence suspension; fines; reputational damage; banking restrictions', 'Sanctions screening system; supply chain due diligence; export control training'),
('Strategic',  'Trading', 'Loss of key supplier relationship disrupting sourcing capability', 'Supplier insolvency; relationship breakdown; exclusivity agreement breach', 'Supply disruption; margin impact; customer delivery failure', 'Supplier diversification; long-term supply agreements; supplier relationship management');
