import { useState } from 'react';
import { useAuth } from '../AuthContext';

export default function DisclaimerModal() {
    const { acceptDisclaimer } = useAuth();
    const [accepting, setAccepting] = useState(false);

    async function handleAccept() {
        setAccepting(true);
        try {
            await acceptDisclaimer();
        } finally {
            setAccepting(false);
        }
    }

    return (
        <div className="disclaimer-overlay">
            <div className="disclaimer-modal">
                <div className="disclaimer-header">
                    <h2 style={{ margin: 0, fontSize: 20 }}>Before you continue</h2>
                </div>
                <div className="disclaimer-body">
                    <p>
                        Qatar Post ERM Workstation is a software tool designed to assist in organizing and documenting
                        governance, risk, and compliance activities. It does not constitute legal,
                        regulatory, accounting, or professional advice of any kind.
                    </p>
                    <p>
                        Outputs generated by this platform — including risk assessments, control frameworks,
                        issue logs, and policy documents — are for internal organizational use only. They
                        should be reviewed by qualified professionals before being relied upon for regulatory
                        submissions, audit responses, or compliance certifications.
                    </p>
                    <p>
                        Certitude Advisory makes no warranties, express or implied, regarding the
                        completeness, accuracy, or fitness for purpose of any content produced through
                        this platform.
                    </p>
                </div>
                <div className="disclaimer-footer">
                    <button
                        className="btn btn-primary"
                        onClick={handleAccept}
                        disabled={accepting}
                    >
                        {accepting ? 'Confirming…' : 'I Understand — Continue'}
                    </button>
                </div>
            </div>
        </div>
    );
}
